/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <GPIO_Driver.h>

void delay(void) {
	for (volatile uint32_t i = 0; i < 200000; i++);
}

GPIO_Handle_t GpioLed;

int main(void){
	GPIO_Handle_t GpioBtn;

	//LED-Konfiguration
	GpioLed.pGPIOx = GPIOD;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_PeriClockControl(GPIOD,ENABLE);

	GPIO_Init(&GpioLed);

	//Button-Konfiguration
	GpioBtn.pGPIOx = GPIOA;
	GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	GpioBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;

	GPIO_PeriClockControl(GPIOA,ENABLE);

	GPIO_Init(&GpioBtn);

	GPIO_WriteToOutputPin(&GpioLed,GPIO_PIN_RESET);

	//IRQ-Konfiguration
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI0,ENABLE);

	while(1);
}


void EXTI0_IRQHandler(void)
{
	delay();
	GPIO_IRQHandling(GPIO_PIN_NO_0); //Setzt Pending Bit im _EXTI-Modul zurück
	GPIO_ToggleOutputPin(&GpioLed);
}
