/**
 ******************************************************************************
 * @file    main.c
 * @author  Auto-generated by STM32CubeIDE
 * @version V1.0
 * @brief   Default main function.
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <GPIO_Driver.h>
#define RED 								1
#define REDYELLOW 							2
#define GREEN 								3
#define YELLOW 								4

void delay_short(void) {
	for (volatile uint32_t i = 0; i < 100000; i++)
		;
}

void delay_5s(void) {
	for (volatile uint32_t i = 0; i < 1000000; i++)
		;
}

void delay_7s(void) {
	for (volatile uint32_t i = 0; i < 1500000; i++)
		;
}

GPIO_Handle_t GPIO_LED_RED, GPIO_LED_ORANGE, GPIO_LED_GREEN;
uint8_t STATE = RED;

int main(void) {
	//LED-GREEN-INIT
	memset(&GPIO_LED_GREEN, 0, sizeof(GPIO_LED_GREEN));
	//LED-Konfiguration
	GPIO_LED_GREEN.pGPIOx = GPIOD;
	GPIO_LED_GREEN.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GPIO_LED_GREEN.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GPIO_LED_GREEN.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	GPIO_LED_GREEN.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GPIO_LED_GREEN.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	//LED-ORANGE-INIT
	memset(&GPIO_LED_ORANGE, 0, sizeof(GPIO_LED_ORANGE));
	//LED-ORANGE-Konfiguration
	GPIO_LED_ORANGE.pGPIOx = GPIOD;
	GPIO_LED_ORANGE.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIO_LED_ORANGE.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GPIO_LED_ORANGE.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	GPIO_LED_ORANGE.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GPIO_LED_ORANGE.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	//LED-RED-INIT
	memset(&GPIO_LED_RED, 0, sizeof(GPIO_LED_RED));
	//LED-RED-Konfiguration
	GPIO_LED_RED.pGPIOx = GPIOD;
	GPIO_LED_RED.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
	GPIO_LED_RED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GPIO_LED_RED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	GPIO_LED_RED.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GPIO_LED_RED.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_PeriClockControl(GPIOD, ENABLE);

	GPIO_Init(&GPIO_LED_GREEN);
	GPIO_Init(&GPIO_LED_ORANGE);
	GPIO_Init(&GPIO_LED_RED);

	GPIO_WriteToOutputPin(&GPIO_LED_GREEN, GPIO_PIN_RESET);
	GPIO_WriteToOutputPin(&GPIO_LED_ORANGE, GPIO_PIN_RESET);
	GPIO_WriteToOutputPin(&GPIO_LED_RED, GPIO_PIN_RESET);

	GPIO_Handle_t GpioBtnD5;
	memset(&GpioBtnD5, 0, sizeof(GpioBtnD5));
	//Button-Konfiguration
	GpioBtnD5.pGPIOx = GPIOD;
	GpioBtnD5.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	GpioBtnD5.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
	GpioBtnD5.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;

	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&GpioBtnD5);

	//IRQ-Konfiguration
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI9_5, ENABLE);

	while (1) {
//		GPIO_WriteToOutputPin(&GPIO_LED_RED, GPIO_PIN_SET);
//		GPIO_WriteToOutputPin(&GPIO_LED_ORANGE, GPIO_PIN_RESET);
//		GPIO_WriteToOutputPin(&GPIO_LED_GREEN, GPIO_PIN_RESET);
//		delay_5s();
//
//		GPIO_WriteToOutputPin(&GPIO_LED_RED, GPIO_PIN_SET);
//		GPIO_WriteToOutputPin(&GPIO_LED_ORANGE, GPIO_PIN_SET);
//		GPIO_WriteToOutputPin(&GPIO_LED_GREEN, GPIO_PIN_RESET);
//		delay_5s();
//
//		GPIO_WriteToOutputPin(&GPIO_LED_RED, GPIO_PIN_RESET);
//		GPIO_WriteToOutputPin(&GPIO_LED_ORANGE, GPIO_PIN_RESET);
//		GPIO_WriteToOutputPin(&GPIO_LED_GREEN, GPIO_PIN_SET);
//		delay_5s();
//
//		GPIO_WriteToOutputPin(&GPIO_LED_RED, GPIO_PIN_RESET);
//		GPIO_WriteToOutputPin(&GPIO_LED_ORANGE, GPIO_PIN_SET);
//		GPIO_WriteToOutputPin(&GPIO_LED_GREEN, GPIO_PIN_RESET);
//		delay_5s();
		switch (STATE) {
		case RED:
			GPIO_WriteToOutputPin(&GPIO_LED_RED, GPIO_PIN_SET);
			GPIO_WriteToOutputPin(&GPIO_LED_ORANGE, GPIO_PIN_RESET);
			GPIO_WriteToOutputPin(&GPIO_LED_GREEN, GPIO_PIN_RESET);
			STATE = REDYELLOW;
			delay_5s();
			break;
		case REDYELLOW:
			GPIO_WriteToOutputPin(&GPIO_LED_RED, GPIO_PIN_SET);
			GPIO_WriteToOutputPin(&GPIO_LED_ORANGE, GPIO_PIN_SET);
			GPIO_WriteToOutputPin(&GPIO_LED_GREEN, GPIO_PIN_RESET);
			STATE = GREEN;
			delay_5s();
			break;
		case GREEN:
			GPIO_WriteToOutputPin(&GPIO_LED_RED, GPIO_PIN_RESET);
			GPIO_WriteToOutputPin(&GPIO_LED_ORANGE, GPIO_PIN_RESET);
			GPIO_WriteToOutputPin(&GPIO_LED_GREEN, GPIO_PIN_SET);
			STATE = YELLOW;
			delay_5s();
			break;
		case YELLOW:
			GPIO_WriteToOutputPin(&GPIO_LED_RED, GPIO_PIN_RESET);
			GPIO_WriteToOutputPin(&GPIO_LED_ORANGE, GPIO_PIN_SET);
			GPIO_WriteToOutputPin(&GPIO_LED_GREEN, GPIO_PIN_RESET);
			STATE = RED;
			delay_5s();
			break;

		}
	}
}

void EXTI9_5_IRQHandler(void) {
	delay_short();	// button-bouncing
	GPIO_IRQHandling(GPIO_PIN_NO_5); //Setzt Pending Bit im _EXTI-Modul zurück

	GPIO_WriteToOutputPin(&GPIO_LED_RED, GPIO_PIN_SET);
	GPIO_WriteToOutputPin(&GPIO_LED_ORANGE, GPIO_PIN_RESET);
	GPIO_WriteToOutputPin(&GPIO_LED_GREEN, GPIO_PIN_RESET);
	STATE = RED;
	delay_7s();
}
